# PipeWire filter-chain configuration for AYN Thor Internal Speaker Tuning
# Credit: adapted from AlsoAmphy's GraphicEQ string in RetroPup's JamesDSP "AYN Thor Audio Fix" preset
# (github.com/ItsRetroPup/AYN-Thor-Tweaks, no licence declared). Same band centres (444/700/1860/3800/11000 Hz) but
# lighter gains than the preset (e.g. 700 Hz -12 dB here vs -17 dB there), so this is NOT the original curve.
# Cuts harsh cabinet resonances between 400Hz-4kHz and protects from sub-bass distortion.

context.modules = [
    { name = libpipewire-module-filter-chain
        flags = [ ifexists nofail ]
        args = {
            node.description = "AYN Thor Tuned Speakers"
            media.name       = "AYN Thor Tuned Speakers"
            filter.graph = {
                nodes = [
                    {
                        type  = builtin
                        name  = eq_band_70
                        label = bq_highpass
                        control = { "Freq" = 80.0 "Q" = 0.707 }
                    }
                    {
                        type  = builtin
                        name  = eq_band_444
                        label = bq_peaking
                        control = { "Freq" = 444.0 "Q" = 1.2 "Gain" = -5.0 }
                    }
                    {
                        type  = builtin
                        name  = eq_band_700
                        label = bq_peaking
                        control = { "Freq" = 700.0 "Q" = 1.0 "Gain" = -12.0 }
                    }
                    {
                        type  = builtin
                        name  = eq_band_1860
                        label = bq_peaking
                        control = { "Freq" = 1860.0 "Q" = 1.0 "Gain" = -15.0 }
                    }
                    {
                        type  = builtin
                        name  = eq_band_3800
                        label = bq_peaking
                        control = { "Freq" = 3800.0 "Q" = 1.2 "Gain" = -16.0 }
                    }
                    {
                        type  = builtin
                        name  = eq_band_11k
                        label = bq_peaking
                        control = { "Freq" = 11000.0 "Q" = 0.7 "Gain" = 3.0 }
                    }
                ]
                links = [
                    { output = "eq_band_70:Out"   input = "eq_band_444:In" }
                    { output = "eq_band_444:Out"  input = "eq_band_700:In" }
                    { output = "eq_band_700:Out"  input = "eq_band_1860:In" }
                    { output = "eq_band_1860:Out" input = "eq_band_3800:In" }
                    { output = "eq_band_3800:Out" input = "eq_band_11k:In" }
                ]
            }
            audio.channels = 2
            audio.position = [ FL FR ]
            capture.props = {
                node.name   = "effect_input.thor_speaker_eq"
                media.class = Audio/Sink
                priority.driver = 1000
                priority.session = 1000
            }
            playback.props = {
                node.name   = "effect_output.thor_speaker_eq"
                node.passive = true
            }
        }
    }
]
